version: "3.8"
services:
  server:
    build:
      context: .  # Set build context to the root directory
      dockerfile: ./server/Dockerfile  # Ensure it points to the correct Dockerfile
    container_name: node-server
    env_file:
      - ./db.env
    ports:
      - "5000:5000"
    networks:
      - app-network

  client:
    build:
      context: .  # Set build context to the root directory to access the client directory
      dockerfile: ./client/Dockerfile  # Specify the Dockerfile location
    container_name: react-client
    ports:
      - "3000:3000"
    networks:
      - app-network
    env_file:
      - ./client/api_base.env

networks:
  app-network:
    driver: bridge